"""Add address to TrashBinSet

Revision ID: 706556f12ad0
Revises: d0e7147bbb62
Create Date: 2024-10-02 14:45:32.480600

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '706556f12ad0'
down_revision = 'd0e7147bbb62'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trash_bin_set',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('trash_bin', schema=None) as batch_op:
        batch_op.add_column(sa.Column('set_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('type', sa.String(length=20), nullable=False))
        batch_op.create_foreign_key(None, 'trash_bin_set', ['set_id'], ['id'])
        batch_op.drop_column('latitude')
        batch_op.drop_column('name')
        batch_op.drop_column('longitude')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trash_bin', schema=None) as batch_op:
        batch_op.add_column(sa.Column('longitude', mysql.FLOAT(), nullable=False))
        batch_op.add_column(sa.Column('name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=False))
        batch_op.add_column(sa.Column('latitude', mysql.FLOAT(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('type')
        batch_op.drop_column('set_id')

    op.drop_table('trash_bin_set')
    # ### end Alembic commands ###
