"""Initial migration with UTC timezone

Revision ID: af72063468ef
Revises: 
Create Date: 2024-11-13 12:16:40.600288

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'af72063468ef'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recycle_log', schema=None) as batch_op:
        batch_op.alter_column('trash_type',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=128),
               type_=sa.String(length=50),
               nullable=False)

    with op.batch_alter_table('trash_bin', schema=None) as batch_op:
        batch_op.alter_column('trash_type',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=128),
               type_=sa.String(length=20),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trash_bin', schema=None) as batch_op:
        batch_op.alter_column('trash_type',
               existing_type=sa.String(length=20),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=128),
               nullable=True)

    with op.batch_alter_table('recycle_log', schema=None) as batch_op:
        batch_op.alter_column('trash_type',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=128),
               nullable=True)

    # ### end Alembic commands ###
